// Generated by CoffeeScript 1.8.0
(function() {
  var PackageBrunch, fs, path;

  path = require('path');

  fs = require('fs');


  /*
    A short plugin in order to add a package.js file with the list of files.
   */

  PackageBrunch = (function() {
    PackageBrunch.prototype.brunchPlugin = true;

    function PackageBrunch(config) {
      var cfg, k, _ref, _ref1, _ref2;
      this.config = config;
      if ('package' in this.config) {
        console.warn('Warning: config.package is deprecated, please move it to config.plugins.package');
      }
      this.options = {
        externalFile: void 0,
        fileName: 'package.js'
      };
      cfg = (_ref = (_ref1 = (_ref2 = this.config.plugins) != null ? _ref2["package"] : void 0) != null ? _ref1 : this.config["package"]) != null ? _ref : {};
      for (k in cfg) {
        this.options[k] = cfg[k];
      }
    }

    PackageBrunch.prototype.onCompile = function(generatedFiles) {
      var filePath, packageInfos;
      packageInfos = require(__dirname + 'package.json');
      filePath = path.join(this.config.paths["public"], this.options.fileName);
      fs.writeFileSync(filePath, JSON.stringify(packageInfos));
    };

    return PackageBrunch;

  })();


  /*
    @module packageBrunch
   */

  module.exports = PackageBrunch;

}).call(this);
